"""
Default values for Mornington Crescent
"""
import re
from collections import defaultdict

_StationString = """Acton Town [Piccadilly] [District]
Aldgate [Metropolitan] [Circle]
Aldgate East [Hammersmith & City] [District]
Alperton [Piccadilly]
Amersham [Metropolitan]
Angel [Northern]
Archway [Northern]
Arnos Grove [Piccadilly]
Arsenal [Piccadilly]
Baker Street [Hammersmith & City] [Circle] [Metropolitan] [Bakerloo] [Jubilee]
Balham [Northern]
Bank [Central] [Waterloo & City] [Northern] [District] [Circle]
Barbican [Hammersmith & City] [Circle] [Metropolitan]
Barking [Hammersmith & City] [District]
Barkingside [Central]
Barons Court [Piccadilly] [District]
Bayswater [Circle] [District]
Becontree [District]
Belsize Park [Northern]
Bermondsey [Jubilee]
Bethnal Green [Central]
Blackfriars [Circle] [District]
Blackhorse Road [Victoria]
Bond Street [Jubilee] [Central]
Borough [Northern]
Boston Manor [Piccadilly]
Bounds Green [Piccadilly]
Bow Road [Hammersmith & City] [District]
Brent Cross [Northern]
Brixton [Victoria]
Bromley-by-Bow [Hammersmith & City] [District]
Buckhurst Hill [Central]
Burnt Oak [Northern]
Caledonian Road [Piccadilly]
Camden Town [Northern]
Canada Water [Jubilee]
Canary Wharf [Jubilee]
Canning Town [Jubilee]
Cannon Street [Circle] [District]
Canons Park [Jubilee]
Chalfont & Latimer [Metropolitan]
Chalk Farm [Northern]
Chancery Lane [Central]
Charing Cross [Bakerloo] [Northern]
Chesham [Metropolitan]
Chigwell [Central]
Chiswick Park [District]
Chorleywood [Metropolitan]
Clapham Common [Northern]
Clapham North [Northern]
Clapham South [Northern]
Cockfosters [Piccadilly]
Colindale [Northern]
Colliers Wood [Northern]
Covent Garden [Piccadilly]
Croxley [Metropolitan]
Dagenham East [District]
Dagenham Heathway [District]
Debden [Central]
Dollis Hill [Jubilee]
Ealing Broadway [Central] [District]
Ealing Common [Piccadilly] [District]
Earl's Court [District] [Piccadilly]
East Acton [Central]
Eastcote [Metropolitan] [Piccadilly]
East Finchley [Northern]
East Ham [Hammersmith & City] [District]
East Putney [District]
Edgware [Northern]
Edgware Road [Hammersmith & City] [Circle] [District]
Edgware Road [Bakerloo]
Elephant & Castle [Bakerloo] [Northern]
Elm Park [District]
Embankment [Northern] [Bakerloo] [Circle] [District]
Epping [Central]
Euston [Northern] [Victoria]
Euston Square [Hammersmith & City] [Circle] [Metropolitan]
Fairlop [Central]
Farringdon [Hammersmith & City] [Circle] [Metropolitan]
Finchley Central [Northern]
Finchley Road [Metropolitan] [Jubilee]
Finsbury Park [Piccadilly] [Victoria]
Fulham Broadway [District]
Gants Hill [Central]
Gloucester Road [Piccadilly] [Circle] [District]
Golders Green [Northern]
Goldhawk Road [Hammersmith & City] [Circle]
Goodge Street [Northern]
Grange Hill [Central]
Great Portland Street [Hammersmith & City] [Circle] [Metropolitan]
Greenford [Central]
Green Park [Jubilee] [Victoria] [Piccadilly]
Gunnersbury [District]
Hainault [Central]
Hammersmith [Piccadilly] [District]
Hammersmith [Hammersmith & City] [Circle]
Hampstead [Northern]
Hanger Lane [Central]
Harlesden [Bakerloo]
Harrow & Wealdstone [Bakerloo]
Harrow-on-the-Hill [Metropolitan]
Hatton Cross [Piccadilly]
Heathrow Terminal 4 [Piccadilly]
Heathrow Terminal 5 [Piccadilly]
Heathrow Terminals 1, 2, 3 [Piccadilly]
Hendon Central [Northern]
High Barnet [Northern]
Highbury & Islington [Victoria]
Highgate [Northern]
High Street Kensington [Circle] [District]
Hillingdon [Metropolitan] [Piccadilly]
Holborn [Piccadilly] [Central]
Holland Park [Central]
Holloway Road [Piccadilly]
Hornchurch [District]
Hounslow Central [Piccadilly]
Hounslow East [Piccadilly]
Hounslow West [Piccadilly]
Hyde Park Corner [Piccadilly]
Ickenham [Metropolitan] [Piccadilly]
Kennington [Northern]
Kensal Green [Bakerloo]
Kensington [District]
Kentish Town [Northern]
Kenton [Bakerloo]
Kew Gardens [District]
Kilburn [Jubilee]
Kilburn Park [Bakerloo]
Kingsbury [Jubilee]
King's Cross St. Pancras [Victoria] [Piccadilly] [Northern] [Circle] [Hammersmith & City] [Metropolitan]
Knightsbridge [Piccadilly]
Ladbroke Grove [Hammersmith & City] [Circle]
Lambeth North [Bakerloo]
Lancaster Gate [Central]
Latimer Road [Hammersmith & City] [Circle]
Leicester Square [Northern] [Piccadilly]
Leyton [Central]
Leytonstone [Central]
Liverpool Street [Circle] [Hammersmith & City] [Metropolitan] [Central]
London Bridge [Northern] [Jubilee]
Loughton [Central]
Maida Vale [Bakerloo]
Manor House [Piccadilly]
Mansion House [Circle] [District]
Marble Arch [Central]
Marylebone [Bakerloo]
Mile End [Central] [Hammersmith & City] [District]
Mill Hill East [Northern]
Moorgate [Northern] [Hammersmith & City] [Circle] [Metropolitan]
Moor Park [Metropolitan]
Morden [Northern]
Mornington Crescent [Northern]
Neasden [Jubilee]
Newbury Park [Central]
North Acton [Central]
North Ealing [Piccadilly]
Northfields [Piccadilly]
North Greenwich [Jubilee]
North Harrow [Metropolitan]
Northolt [Central]
North Wembley [Bakerloo]
Northwick Park [Metropolitan]
Northwood [Metropolitan]
Northwood Hills [Metropolitan]
Notting Hill Gate [Circle] [District] [Central]
Oakwood [Piccadilly]
Old Street [Northern]
Osterley [Piccadilly]
Oval [Northern]
Oxford Circus [Bakerloo] [Victoria] [Central]
Paddington [Bakerloo] [Circle] [District]
Paddington [Circle] [Hammersmith & City]
Park Royal [Piccadilly]
Parsons Green [District]
Perivale [Central]
Piccadilly Circus [Bakerloo] [Piccadilly]
Pimlico [Victoria]
Pinner [Metropolitan]
Plaistow [Hammersmith & City] [District]
Preston Road [Metropolitan]
Putney Bridge [District]
Queensbury [Jubilee]
Queen's Park [Bakerloo]
Queensway [Central]
Ravenscourt Park [District]
Rayners Lane [Metropolitan] [Piccadilly]
Redbridge [Central]
Regent's Park [Bakerloo]
Richmond [District]
Rickmansworth [Metropolitan]
Roding Valley [Central]
Royal Oak [Circle] [Hammersmith & City]
Ruislip [Metropolitan] [Piccadilly]
Ruislip Gardens [Central]
Ruislip Manor [Metropolitan] [Piccadilly]
Russell Square [Piccadilly]
Seven Sisters [Victoria]
Shepherd's Bush [Central]
Shepherd's Bush Market [Circle] [Hammersmith & City]
Sloane Square [Circle] [District]
Snaresbrook [Central]
South Ealing [Piccadilly]
Southfields [District]
Southgate [Piccadilly]
South Harrow [Piccadilly]
South Kensington [Piccadilly] [Circle] [District]
South Kenton [Bakerloo]
South Ruislip [Central]
Southwark [Jubilee]
South Wimbledon [Northern]
South Woodford [Central]
Stamford Brook [District]
Stanmore [Jubilee]
Stepney Green [Hammersmith & City] [District]
St. James's Park [Circle] [District]
St. John's Wood [Jubilee]
Stockwell [Victoria] [Northern]
Stonebridge Park [Bakerloo]
St. Paul's [Central]
Stratford [Central]  [Jubilee]
Sudbury Hill [Piccadilly]
Sudbury Town [Piccadilly]
Swiss Cottage [Jubilee]
Temple [Circle] [District]
Theydon Bois [Central]
Tooting Bec [Northern]
Tooting Broadway [Northern]
Tottenham Court Road [Northern] [Central]
Tottenham Hale [Victoria]
Totteridge & Whetstone [Northern]
Tower Hill [Circle] [District]
Tufnell Park [Northern]
Turnham Green [District]
Turnpike Lane [Piccadilly]
Upminster [District]
Upminster Bridge [District]
Upney [District]
Upton Park [Hammersmith & City] [District]
Uxbridge [Metropolitan] [Piccadilly]
Vauxhall [Victoria]
Victoria [Victoria] [Circle] [District]
Walthamstow Central [Victoria]
Wanstead [Central]
Warren Street [Northern] [Victoria]
Warwick Avenue [Bakerloo]
Waterloo [Bakerloo] [Northern] [Waterloo & City] [Jubilee]
Watford [Metropolitan]
Wembley Central [Bakerloo]
Wembley Park [Metropolitan] [Jubilee]
West Acton [Central]
Westbourne Park [Circle] [Hammersmith & City]
West Brompton [District]
West Finchley [Northern]
West Ham [Jubilee] [Hammersmith & City] [District]
West Hampstead [Jubilee]
West Harrow [Metropolitan]
West Kensington [District]
Westminster [Circle] [District] [Jubilee]
West Ruislip [Central]
Whitechapel [Hammersmith & City] [District]
White City [Central]
Willesden Green [Jubilee]
Willesden Junction [Bakerloo]
Wimbledon [District]
Wimbledon Park [District]
Woodford [Central]
Wood Green [Piccadilly]
Wood Lane [Circle] [Hammersmith & City]
Woodside Park [Northern]"""

_matches = map(lambda line: re.search("^([^\[\]]*?)\s*((\[[^\[\]]*\]\s*)*)$", line), _StationString.split("\n"))

Stations = defaultdict(list)
Lines    = set()

for match in _matches:
    for line in re.compile("\[([^\[\]]*)\]").findall(match.group(2)):
        Stations[match.group(1)].append(line)
        Lines.add(line)
